<?php

namespace Jackwander\ModuleMaker\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class Init extends Command
{
    use \Jackwander\ModuleMaker\Commands\Traits\InteractsWithStubs;

    protected $signature = 'jw:init';
    protected $description = 'Initialize the Core module with local base classes and update configuration';

    protected $files;

    public function __construct(Filesystem $files)
    {
        parent::__construct();
        $this->files = $files;
    }

    public function handle()
    {
        $this->info("🚀 Initializing Module Maker Core...");

        $corePath = app_path('Modules/Core');
        
        if (!$this->files->exists($corePath)) {
            $this->files->makeDirectory($corePath, 0755, true);
        }

        // 1. Generate Base Classes in App\Modules\Core
        $this->generateBaseClass('core-model', "{$corePath}/BaseModel.php");
        $this->generateBaseClass('core-controller', "{$corePath}/BaseApiController.php");
        $this->generateBaseClass('core-service', "{$corePath}/BaseService.php");

        // 2. Localize the configuration
        $this->updateConfiguration();

        $this->newLine();
        $this->info("✅ Initialization complete!");
        $this->line("Future modules generated via <fg=cyan>jw:make-model --all</> will now extend your local Core classes.");
    }

    /**
     * Generate a file from a stub.
     */
    protected function generateBaseClass($stub, $path)
    {
        if ($this->files->exists($path)) {
            $this->components->twoColumnDetail(basename($path), '<fg=yellow>Skipped (Exists)</>');
            return;
        }

        $content = $this->getStubContent($stub, []);
        $this->files->put($path, $content);
        $this->components->twoColumnDetail(basename($path), '<fg=green>Created</>');
    }

    /**
     * Write the localized configuration to the host application.
     */
    protected function updateConfiguration()
    {
        $configPath = config_path('module-maker.php');
        
        $configContent = <<<'PHP'
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Package Paths & Namespaces
    |--------------------------------------------------------------------------
    |
    | Configure the root directory and root namespace for your modules.
    | By default, they will be placed in the `app/Modules` directory.
    |
    */
    'paths' => [
        'modules' => base_path('app/Modules'),
        'api_prefix' => 'api/v1',
    ],

    'namespaces' => [
        'root' => 'App\\Modules',
    ],

    /*
    |--------------------------------------------------------------------------
    | Base Classes (Localized to Core)
    |--------------------------------------------------------------------------
    |
    | These classes were generated by jw:init and are located in 
    | App\Modules\Core. You can customize them to your needs.
    |
    */
    'base_classes' => [
        'service'        => \App\Modules\Core\BaseService::class,
        'api_controller' => \App\Modules\Core\BaseApiController::class,
        'model'          => \App\Modules\Core\BaseModel::class,
    ]
];
PHP;

        $this->files->put($configPath, $configContent);
        $this->components->twoColumnDetail('config/module-maker.php', '<fg=green>Localized</>');
    }
}
