<?php

namespace Jackwander\ModuleMaker\AI;

use Illuminate\Support\Facades\File;
use Jackwander\ModuleMaker\AI\Contracts\Section;
use Jackwander\ModuleMaker\AI\Sections\AiRulesSection;
use Jackwander\ModuleMaker\AI\Sections\ArchitectureSection;
use Jackwander\ModuleMaker\AI\Sections\ConventionsSection;
use Jackwander\ModuleMaker\AI\Sections\GeneratorsSection;
use Jackwander\ModuleMaker\AI\Sections\ModulesSection;
use Jackwander\ModuleMaker\AI\Sections\PromptsSection;
use Jackwander\ModuleMaker\AI\Sections\ToolingSection;
use Jackwander\ModuleMaker\AI\Sections\WorkflowSection;
use Jackwander\ModuleMaker\AI\Support\Depth;
use Jackwander\ModuleMaker\AI\Support\ProjectSnapshot;
use Jackwander\ModuleMaker\Commands\Traits\InteractsWithStubs;

class ContextBuilder
{
    use InteractsWithStubs;

    public function __construct(protected CommandCatalog $catalog)
    {
    }

    /** @return array<string, Section> keyed by section key */
    public function sections(): array
    {
        $sections = [
            new ArchitectureSection(),
            new ConventionsSection(),
            new GeneratorsSection($this->catalog),
            new AiRulesSection(),
            new ModulesSection(),
            new WorkflowSection(),
            new ToolingSection(),
            new PromptsSection(),
        ];

        $keyed = [];
        foreach ($sections as $section) {
            $keyed[$section->key()] = $section;
        }

        return $keyed;
    }

    public function outputPath(): string
    {
        return config('module-ai.output_path') ?: base_path('.ai');
    }

    /** @return string[] relative paths that build() would write */
    public function plannedFiles(Depth $depth): array
    {
        $files = [];

        if ($depth !== Depth::Summary) {
            foreach ($this->sections() as $key => $section) {
                if ($this->sectionEnabled($key)) {
                    $files[] = ".ai/{$key}.md";
                }
            }
        }

        $files[] = '.ai/summary.md';

        return $files;
    }

    /** @return array<string, string> file => status */
    public function build(ProjectSnapshot $snapshot, Depth $depth): array
    {
        $out = $this->outputPath();
        File::ensureDirectoryExists($out);

        $results = [];

        if ($depth !== Depth::Summary) {
            foreach ($this->sections() as $key => $section) {
                if (! $this->sectionEnabled($key)) {
                    continue;
                }

                $content = $this->stamp($section->render($snapshot, $depth), $snapshot);
                $results["{$key}.md"] = $this->put("{$out}/{$key}.md", $content);
            }
        }

        $results['summary.md'] = $this->put("{$out}/summary.md", $this->buildSummary($snapshot));

        return $results;
    }

    public function buildSummary(ProjectSnapshot $snapshot): string
    {
        $bridgeNote = $snapshot->bridgeActive
            ? 'Generated classes extend the local bridge in `App\\Modules\\Core` (jw:init active) — put project-wide logic there.'
            : 'The `App\\Modules\\Core` bridge is not initialized; run `php artisan jw:init` before heavy customization.';

        $tooling = array_keys(array_filter($snapshot->tooling));

        $modulesLine = $snapshot->modules
            ? 'Existing modules: ' . implode(', ', array_keys($snapshot->modules)) . '.'
            : 'No modules exist yet.';

        return $this->stamp($this->getStubContent('ai/summary', [
            'laravelVersion' => $snapshot->laravelVersion,
            'phpVersion' => $snapshot->phpVersion,
            'packageVersion' => $snapshot->packageVersion,
            'modulesPath' => $snapshot->modulesPath,
            'rootNamespace' => $snapshot->rootNamespace,
            'apiPrefix' => $snapshot->apiPrefix,
            'bridgeNote' => $bridgeNote,
            'generatorTable' => $this->catalog->markdownTable(),
            'toolingLine' => $tooling ? implode(', ', $tooling) : 'none detected',
            'testCommand' => $snapshot->testCommand(),
            'modulesLine' => $modulesLine,
        ]), $snapshot);
    }

    protected function sectionEnabled(string $key): bool
    {
        return (bool) config('module-ai.sections.' . str_replace('-', '_', $key), true);
    }

    protected function stamp(string $content, ProjectSnapshot $snapshot): string
    {
        $header = "<!-- Generated by jw:ai:init (module-maker v{$snapshot->packageVersion}). Do not edit; regenerate with `php artisan jw:ai:init --refresh`. -->\n\n";

        return $header . ltrim($content) . "\n";
    }

    protected function put(string $path, string $content): string
    {
        $status = File::exists($path)
            ? (File::get($path) === $content ? 'unchanged' : 'updated')
            : 'created';

        if ($status !== 'unchanged') {
            File::put($path, $content);
        }

        return $status;
    }
}
